services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.servicediscovery.processor:
        class: Garlic\HealthCheck\Service\Processor\ServiceDiscoveryProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
        tags:
            - { name: 'enqueue.client.processor', topicName: 'serviceDiscovery'}

    app.servicediscovery.init:
        class: Garlic\HealthCheck\Command\HealthCheckCommand
        arguments:
            - "healthcheck:init"
            - "@kernel"
            - "@lock.service"
        tags:
            - { name: 'console.command', command: 'healthcheck:init'}

    lock.service:
        class: Garlic\HealthCheck\Service\Lock\LockService
        public: true
        arguments:
            - "%env(REDIS_HOST)%"
            - "%env(REDIS_PORT)%"
