services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.servicediscovery.processor:
        class: Garlic\HealthCheck\Service\Processor\ServiceDiscoveryProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
        tags:
            - { name: 'enqueue.client.processor', topicName: 'serviceDiscovery'}

    Garlic\Bus\Service\File\FileHandlerService:
        public: true
        arguments:
            - "%env(HOST_URL)%"
            - "%env(UPLOAD_DIR)%"